Update Policy Sentry to pick latest commit
Was facing error in recommend_groups due to outdated list 
policy_is_write_access 
TypeError: 'NoneType' object is not iterable